Add missing <cstdint> includes
Fixes the following compilation errors in clang15 & gcc13:
- error: no type named 'uint64_t' in namespace 'std'
- error: ‘uint8_t’ is not a member of ‘std’